apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-service
  namespace: production
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend-prod
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-prod-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/acme-challenge-type: "http01"	
    cert-manager.io/cluster-issuer: "letsencrypt-frontend-prod"
spec:
  rules:
  ## Service Location n Characters
  - host: p-frontend.miqbalnawawi.site
    http:
      paths:
      - backend:
          serviceName: frontend-prod-service
          servicePort: 3000
        path: /
  tls:
    - hosts:
      - p-frontend.miqbalnawawi.site
      secretName: frontend-prod-tls
