apiVersion: v1
kind: Service
metadata:
  name: backend-prod-service
  namespace: production
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: backend-prod
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-prod-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/acme-challenge-type: "http01"	
    cert-manager.io/cluster-issuer: "letsencrypt-backend-prod"
spec:
  rules:
  ## Service Location n Characters
  - host: p-backend.miqbalnawawi.site
    http:
      paths:
      - backend:
          serviceName: backend-prod-service
          servicePort: 4000
        path: /
  tls:
    - hosts:
      - p-backend.miqbalnawawi.site
      secretName: backend-prod-tls
